apiVersion: v1
kind: Secret
metadata:
  name: bank-marketing-api-secrets
  namespace: mlops-production
type: Opaque
stringData:
  API_KEY: "change-me-locally"
  MLFLOW_TRACKING_URI: "http://mlflow:5000"