{
 "title": "Bank Marketing – Model Performance",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Prediction Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(prediction_latency_seconds_sum[5m])) \n / \nsum(rate(prediction_latency_seconds_count[5m]))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Latency Distribution (Histogram Buckets)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(prediction_latency_seconds_bucket[5m])) by (le)",
     "legendFormat": "le={{le}}"
    }
   ]
  },
  {
   "title": "Request Throughput (req/s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler=\"/api/v1/predict\"}[1m]))"
    }
   ]
  }
 ]
}