{
 "title": "Bank Marketing – System Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"bank-marketing-api.*\"}[2m])) by (pod)",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "API Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"bank-marketing-api.*\"}) by (pod)",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"bank-marketing-api.*\"})"
    }
   ]
  },
  {
   "title": "Current HPA Replicas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"bank-marketing-api\"}"
    }
   ]
  }
 ]
}