global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape kube-prometheus-stack default metrics
  - job_name: "kubernetes-apiservers"
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_name

  # Scrape your Bank Marketing API FastAPI metrics
  - job_name: "bank-marketing-api"
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - bank-marketing-api.mlops-production.svc.cluster.local:8000